AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'it']
  Exclude:
    - 'Rakefile'
    - '**/*.rake'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 15

Style/HashSyntax:
  Exclude:
    # for task :foo => :bar definitions
    - '**/Rakefile'
    - '**/*.rake'
    - '**/*.rake.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
